##################################################
# Configuración general de la aplicación
##################################################
spring.application.name=servicio-rest

server.port=8080

##################################################
# Configuración de la base de datos (PostgreSQL local)
##################################################
spring.datasource.url=jdbc:postgresql://localhost:5432/tutor
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

##################################################
# Configuración de JPA / Hibernate
##################################################
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

##################################################
# Swagger / OpenAPI
##################################################
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs

##################################################
# JWT
##################################################
jwt.secret=EstaEsMiClaveSuperSecretaParaJWT123456
jwt.expiration=3600000

##################################################
# Spring Security
##################################################
spring.security.user.name=admin
spring.security.user.password=MiPassword123
spring.security.enabled=false
