##################################################
# Configuración general de la aplicación
##################################################
spring.application.name=servicio-rest

server.port=8080

##################################################
# Configuración de la base de datos (PostgreSQL)
##################################################
#spring.datasource.url=jdbc:postgresql://postgres_db:5432/tutor

 spring.datasource.url=jdbc:postgresql://localhost:5432/tutor
spring.datasource.username=admin
spring.datasource.password=admin123
spring.datasource.driver-class-name=org.postgresql.Driver

##################################################
# Configuración de JPA / Hibernate
##################################################
# ddl-auto puede ser: none, validate, update, create, create-drop
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

# Mostrar las consultas SQL en la consola
spring.jpa.show-sql=true

# Dialecto de PostgreSQL para Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# URL del Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
# URL base de los endpoints OpenAPI
springdoc.api-docs.path=/v3/api-docs


# Configuración JWT
jwt.secret=EstaEsMiClaveSuperSecretaParaJWT123456
jwt.expiration=3600000



spring.security.user.name=admin
spring.security.user.password=MiPassword123


spring.security.enabled=false


#minio.endpoint=${MINIO_ENDPOINT:http://localhost:9000}
#minio.user=${MINIO_USER:minioadmin}
#minio.pass=${MINIO_PASS:minioadmin}

minio.endpoint=${MINIO_ENDPOINT:http://minio:9000}
minio.user=${MINIO_USER:minioadmin}
minio.pass=${MINIO_PASS:minioadmin}

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
minio.bucket.usuarios=usuarios